# Generated by Django 5.2.7 on 2025-10-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventalbum',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='yearalbum',
            options={'ordering': ['-year'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.RemoveField(
            model_name='eventalbum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventalbum',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='eventalbum',
            name='moderation_comment',
        ),
        migrations.RemoveField(
            model_name='eventalbum',
            name='moderation_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='moderation_comment',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='moderation_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='yearalbum',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='yearalbum',
            name='moderation_comment',
        ),
        migrations.RemoveField(
            model_name='yearalbum',
            name='moderation_date',
        ),
        migrations.AlterField(
            model_name='eventalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='eventalbum',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='eventalbum',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventalbum',
            name='year_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='media_archive.yearalbum', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='event_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media_archive.eventalbum', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='yearalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='yearalbum',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='yearalbum',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='yearalbum',
            name='year',
            field=models.CharField(max_length=9, verbose_name='Учебный год'),
        ),
    ]
