# Generated by Django 5.2.7 on 2025-10-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0003_remove_eventalbum_year_album_schoolclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalbum',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='media_archive.schoolclass', verbose_name='Класс'),
        ),
    ]
