# Generated by Django 5.2.7 on 2025-11-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0004_alter_eventalbum_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
